# Generated by Django 5.1.6 on 2025-02-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullStackTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Member',
        ),
    ]
